name: CLOMP

on: [push, pull_request]  

jobs:

  complete_workflow:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name:  Run CLOMP
        run: |
          NXF_ANSI_LOG=false NXF_VER=20.01.0 nextflow run main.nf             -profile testing             --INPUT_FOLDER test_data/             --INPUT_SUFFIX .fastq.gz             --ENTREZ_EMAIL vpeddu@uw.edu             --OUTDIR test_data/out/             -work-dir test_data/work/             --SNAP_INDEXES "test_data/test_db_1/,test_data/test_db_2/,test_data/test_db_3/"             --TRIMMOMATIC_OPTIONS ":2:30:10 SLIDINGWINDOW:4:20"             --TRIMMOMATIC_JAR_PATH test_data/trimmomatic-0.38.jar             -with-docker ubuntu:18.04             --KRAKEN_DB_PATH test_data/kraken_db/             --BWT_DB_LOCATION test_data/bt2/             --TRIMMOMATIC_ADAPTER_PATH test_data/adapters.fa             --BWT_DB_PREFIX human_ref -with-trace -resume --FASTQ_MIN_READ 10
